config/routes.rb
Cards::Application.routes.draw do

  root 'blackjack#game'
  get '/blackjack' => 'blackjack#game'


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blackjack_controller.rb
class BlackjackController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blackjack_helper.rb
module BlackjackHelper
end

app/views/blackjack/game.html.erb
<div class="page-header">
  <h1>Blackjack</h1>
</div>

<div class="row">
  <div class="span8">
    <div class="row actions">
      <div class="span 8">
        <%= link_to "Take Another Card", "#", class: 'btn btn-primary' %>
        <%= link_to "Start Over", "#", class: 'btn btn-primary' %>
      </div>
    </div>
    <div class="row">
      <div class="span8">
      <%= image_tag 'cards/2_of_hearts.png', width: 100 %>
      <%= image_tag 'cards/3_of_spades.png', width: 100 %>
      </div>
    </div>
  </div>
  <div class="span4">
    <h3>Challenges</h3>
    <strong>Consider an Ace to have a value of 1.</strong>
    <ol>
      <li>Deal two random cards from the deck.</li>
      <li>If the cards value 21, tell them they won!</li>
      <li>If the cards are over 21, tell them they lost.</li>
      <li>If they haven't won nor lost, allow them to take another card.</li>
      <li>Consider an Ace to have a value of 1 or 11, whichever is in the player's favor.</li>
    </ol>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Cards</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>


  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to "Cards", root_url, class: 'brand' %>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Blackjack", blackjack_url %></li>
            <li><%= link_to "Poker", '#' %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">

    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">&times;</a>
        <%= msg %>
      </div>
    <% end %>

    <%= yield %>

  </div>

</body>
</html>